name: VitalTrash
version: @version@
main: com.tamrielnetwork.vitaltrash.VitalTrash
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to open a trash interface.
commands:
  trash:
    description: "Main command"
    usage: "/trash"
permissions:
  vitaltrash.trash:
    description: "Permission to toggle crafting interface"
    default: op